kind: pipeline
type: kubernetes
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello 

- name: fr
  image: alpine
  commands:
  - echo bonjour monde

  
      
      

      

      

      
     

      

